Respect image URLs while annotating multiple images. Closes #126
symbench/scm pull request #127
Opened 2021-07-02 15:45 UTC by umesh-timalsina

2021-07-02 16:38 UTC, brollb requested changes
I think it would be better to actually make a new `Image` class which contains an `id` and `contents`. This would make the method signature cleaner and avoid potentially annoying issues like URL lists of a different size or something annoying like that.

2021-07-02 16:41 UTC, brollb commented on circuit_recognizer/circuit_recognizer/recognition.py
> +            if url is not None:
It would also allow us to avoid adding too many things like these. I generally like to avoid adding a bunch of checks for if an argument is `None`. Especially in this case where `url` is sometimes a required argument and isn't really optional. (It is required if the `image` is not the same as the target of the annotation snippets.)

2021-07-02 18:06 UTC, umesh-timalsina commented
Here by `id` we mean the `url` for the image right?

2021-07-02 18:18 UTC, brollb commented
Yeah, at least in this context. If we are running it from the command line, it should probably be the absolute file path

2021-07-02 18:22 UTC, umesh-timalsina commented
Okay, I would probably opt for some name other than `id` because, a `ComponentAnnotation` will also have an id associated with it.

2021-07-05 20:43 UTC, brollb reviewed
Looks good! I added a stylistic comment (and another below):

> Okay, I would probably opt for some name other than id because, a ComponentAnnotation will also have an id associated with it just to make sure we are not confusing the two terms.

I am not sure that I see this as an issue since they are different types and can certainly have a member attribute of the same name. In this specific case, I am not too worried about it being too confusing since different types could have different conventions for their IDs. If I am going to nit pick, I am not sure `resolved_id` really is much different from `id` as I would expect the latter to be resolved to some canonical form anyway (referring to the use of `realpath`) so checking that two images are the same can be achieved to some reasonable degree.

Alternatively, we could rename it to something like `source` instead. The argument could be made that if an ID is meant to be a canonical form that could be used for checking equivalence, etc, maybe something like a hash would be a better candidate anyway. `source` also is maybe a little more clear about what the field represents anyway as it isn't just some arbitrary ID (or UUID).

2021-07-05 20:43 UTC, brollb commented on circuit_recognizer/circuit_recognizer/server.py
> +            content=cv2.imread(get_image_path(url), cv2.IMREAD_UNCHANGED),
This read a little backwards to me since I expected the id to be the first argument. Not a big deal (and maybe I am just a bit tired :) ) but I am used to seeing IDs as the first argument.

2021-07-05 20:43 UTC, brollb commented on circuit_recognizer/circuit_recognizer/server.py
> +            content=cv2.imread(get_image_path(url), cv2.IMREAD_UNCHANGED),
(same as the usage for the CLI)

2021-07-05 20:52 UTC, brollb approved these changes

2021-07-05 21:04 UTC, umesh-timalsina commented on circuit_recognizer/circuit_recognizer/server.py
> +            content=cv2.imread(get_image_path(url), cv2.IMREAD_UNCHANGED),
Resolved by refactoring `resolved_id` to `source`.

2021-07-05 21:11 UTC, merged