OCR Helper for named port annotation. Closes #239
symbench/scm pull request #240
Opened 2021-09-22 18:28 UTC by umesh-timalsina

## Client Side
- [ ] Adding Plugin
- [ ] Comment Widget Changes

## Server Side
- [ ] OCR on annotation snippet with tessaract
- [ ] REST endpoint for annotation

2021-09-22 22:10 UTC, umesh-timalsina commented
This PR has added the necessary features, however, updating a `selection` to an annotation is causing issues leading to following bugs:

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at getLabeledPorts (AnnotoriousPortsAnnotatorPlugin.js:50)
    at hasFullyLabeledPorts (AnnotoriousPortsAnnotatorPlugin.js:63)
    at requestComponentDetection (AnnotoriousPortsAnnotatorPlugin.js:90)
    at handleAnnotationUpdate (AnnotoriousPortsAnnotatorPlugin.js:99)
    at OSDAnnoWithEvents.emit (index.js:36)
    at OSDAnnoWithEvents.js:30
    at n.emit (openseadragon-annotorious.min.js:2)
    at Object.onAnnotationUpdated (openseadragon-annotorious.min.js:2)
    at a.<anonymous> (openseadragon-annotorious.min.js:2)
    at openseadragon-annotorious.min.js:2
```

Which needs further digging.

2021-09-23 14:11 UTC, brollb reviewed
I added some comments while looking through the code but haven't tried it yet. It looks like it will be a cool addition!

2021-09-23 14:11 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        await annotator.updateSelected(results, false);
It would be a good idea to check that the selected annotation is still the one we are performing OCR on since the previous call is async.

2021-09-23 14:11 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        const response =  await fetch(ocrURL, {
As a general thought, it would probably be good to refactor the calls to the server API so we don't have all these extra calls to `fetch`. I am thinking of something like a new class like `RecognitionAPI(baseUrl)`. (It doesn't belong in this PR but I wanted to mention it anyway.)

2021-09-23 14:11 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        if(annotationMode.isPortMode()) {
We probably want to only use OCR if:
- the port is "Port"
- the label is "Text" (assuming we add a "text" class for labeling attributes later)

2021-09-23 14:11 UTC, brollb commented on circuit_recognizer/circuit_recognizer/server.py
> +@app.post("/snippet-ocr")
As a minor comment, we probably don't need to include "snippet" in the path since that is a bit different from the other endpoints (ie, it isn't "/snippet-ports"). Or is there another reason to name it like this?

2021-09-23 14:26 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        await annotator.updateSelected(results, false);
I think this call may be the source of errors, looking at the OSD-annotorious [API](https://recogito.github.io/annotorious/api-docs/osd-plugin/#updateselected), it looks like this will trigger `createAnnotation` or `updateAnnotation` event. Regardless, if you are in port mode and there's an active selection,the selected annotation is not actually an `annotation` its just a svg rect with fragmentsselector (no ID, id for the selection-> annotation conversion is done in server) we could do that check if so desired, however, I think without canceling the current selection(Although there might be rare cases where `cancelSelected` is called programmitically ), I don't think annotoroious will allow you to select a different one.

2021-09-23 14:26 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        const response =  await fetch(ocrURL, {
Agreed, we should refactor the API.

2021-09-23 14:27 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        if(annotationMode.isPortMode()) {
Yeah, the plugin can listen to multiple events if so desired, however, the current setup will be a problem where we assume that these ports will always be named (this might not be the case always).

2021-09-23 14:28 UTC, umesh-timalsina commented on circuit_recognizer/circuit_recognizer/server.py
> +@app.post("/snippet-ocr")
The `snippet` prefix is there because, one could argue that when making an `ocr` call, you could run ocr on the whole annotation target image, not just on the snippet yielded by the fragment selector for the annotation.

2021-09-23 15:00 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        await annotator.updateSelected(results, false);
I am not sure I follow. The issue I was referring to:
- Select a port (in port mode)
- The request is made to the server
- Click another annotation (perhaps already created port for the same component)
- The response from the server is received
- The text recognized from the first selection is applied to the second selection.

2021-09-23 15:06 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        if(annotationMode.isPortMode()) {
If they aren't named, we probably shouldn't perform OCR. I would perform OCR on port update if the port's label is one of the types that is expected to contain text.

2021-09-23 22:11 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/SelectedSnippetOCRPlugin.js
> +        await annotator.updateSelected(results, false);
There is one issue, I think we can shortcut it even more:

- Select a port (in port mode)
- Click one of the available port labels and send OCR request to the server
- The response from the server is received, the recognized text is populated to the comment widget
- User decides to edit/keep/discard

The workflow will save couple of clicks compared to one mentioned in https://github.com/symbench/scm/pull/240#discussion_r714887142

2021-11-01 22:20 UTC, brollb requested changes
Nice work. I left some comments below.

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/__tests__/ComponentLabelWidget.spec.js
> +const addSelector = jest.fn();
This shouldn't be needed should it?

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/RecognitionAPI.ts
> +            purpose: purpose,
Do we need to send the purpose?

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        const componentLabelWidget = ComponentLabelWidgetFactory(ontology, annotationMode, () => annotator.getAnnotations(), api);
This will probably have some merge conflicts since `annotationMode` was refactored

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        SWITCH_ANNOTATION_MODE
Probably gonna be a merge conflict. It will need to be deleted.

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/ComponentLabelWidget.ts
> +    const valueField = detailElements.find(field => field.placeholder === 'value');
Why not do this in the on change event listener? Won't this make it impossible to delete OCR results? (Deleting the value should result in `shouldRequestOCR` to be true again, right?)

2021-11-01 22:20 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/ComponentLabelWidget.ts
> +            args.recognitionApi = recognitionApi;
It would be nice not to tack values in ad-hoc like this. A couple options:
- the change event handler could be refactored to be an input argument
- the api could be passed as another argument (though there are a lot already)
- another type could be created that bundles these together and consolidates the number of args

2021-11-01 22:35 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/__tests__/ComponentLabelWidget.spec.js
> +const addSelector = jest.fn();
This is necessary/can be a nop as well.

2021-11-01 22:35 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/RecognitionAPI.ts
> +            purpose: purpose,
Yeah. This should probably be removed since we don't use it in the server.

2021-11-02 17:27 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/__tests__/ComponentLabelWidget.spec.js
> +const addSelector = jest.fn();
Removed this.

2021-11-02 17:27 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        const componentLabelWidget = ComponentLabelWidgetFactory(ontology, annotationMode, () => annotator.getAnnotations(), api);
Refactored.

2021-11-02 17:27 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        SWITCH_ANNOTATION_MODE
Refactored/Deleted.

2021-11-02 17:28 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/ComponentLabelWidget.ts
> +            args.recognitionApi = recognitionApi;
This change was super easy after #318 and not an issue anymore.

2021-11-02 17:42 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/ComponentLabelWidget.ts
> +    const valueField = detailElements.find(field => field.placeholder === 'value');
A better way to handle this IMO is to send OCR requests on selection (I.e. only once). No overriding of user intent should be done afterwards i.e. when the selection gets converted to annotation.

2021-11-02 17:42 UTC, umesh-timalsina commented
LGTM!!!

2021-11-02 18:58 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/ComponentLabelWidget.ts
> +    const valueField = detailElements.find(field => field.placeholder === 'value');
When a region is selected, you don't know what the label is (and, as a result, don't know if OCR is applicable). When a label is selected, this is known and the form is dynamically updated to reflect any "tag details" values. It seems pretty straightforward to just prepopulate the form with default values when the selected label is an attribute (ie, the label has "details" defined in the ontology), imo. Is there something problematic with this approach that I am overlooking?

2021-11-08 15:16 UTC, brollb commented
Hmm... Now I am getting the following error. I can check it out.

![DeepinScreenshot_select-area_20211108091638](https://user-images.githubusercontent.com/4982789/140767780-ecc44f15-a350-4d9a-98c5-281204d2351b.png)

2021-11-08 16:31 UTC, brollb approved these changes

2021-11-08 16:32 UTC, merged