Add inferred_from field to Annotation Model. Closes #73
symbench/scm pull request #74
Opened 2021-06-11 16:33 UTC by umesh-timalsina

2021-06-11 22:07 UTC, umesh-timalsina commented
It looks like you can add inferred fields using [`identities`](https://www.w3.org/TR/annotation-model/#other-identities) with the W3C spec. c69fa65 Adds such relationship.

2021-06-14 20:15 UTC, brollb commented on circuit_recognizer/circuit_recognizer/annotations.py
> +    cannonical: Optional[str] = None
I believe this should be `canonical` (two total "n"s), right?

2021-06-14 20:33 UTC, umesh-timalsina commented on circuit_recognizer/circuit_recognizer/annotations.py
> +    cannonical: Optional[str] = None
Oops My Bad, can even make an excuse for British spelling here. :)

2021-06-16 14:16 UTC, brollb requested changes
Overall, this looks great. One minor stylistic suggestion: instead of adding a flag to `copy`, it might be nicer to always copy the canonical representation. It isn't obvious what `infer` does at a glance and it seems that recording the canonical representation is always the intended behavior.

2021-06-16 14:16 UTC, brollb commented on circuit_recognizer/circuit_recognizer/annotations.py
> +            copy.cannonical = self.id
typo

2021-06-16 14:16 UTC, brollb commented on circuit_recognizer/circuit_recognizer/annotations.py
> +                port_copy.cannonical = original_port.id
typo in canonical

2021-06-16 14:55 UTC, brollb commented on circuit_recognizer/circuit_recognizer/annotations.py
> +        if not self.canonical:
Just using `assert` would probably be a little more concise but not a huge deal

2021-06-16 15:00 UTC, umesh-timalsina commented on circuit_recognizer/circuit_recognizer/annotations.py
> +        if not self.canonical:
Yeah, in this case `ValueError` makes more sense IMO.

2021-06-16 15:08 UTC, brollb commented on circuit_recognizer/circuit_recognizer/annotations.py
> +        if not self.canonical:
Hmm... I am not sure I follow. Wouldn't a value error imply there is something wrong with the value of `relation`? In this case, the problem seems to be that the method is invalid for instances without the appropriate state. (For reference, [here](https://docs.python.org/3/library/exceptions.html#ValueError) is the official description for ValueError I am looking at.)

2021-06-16 15:09 UTC, umesh-timalsina commented
> Overall, this looks great. One minor stylistic suggestion: instead of adding a flag to `copy`, it might be nicer to always copy the canonical representation. It isn't obvious what `infer` does at a glance and it seems that recording the canonical representation is always the intended behavior.

Two comments on this:
1. Isn't it the case that copy is generally used to create the exact replica of the object under consideration? 
2. In this case we might have to consider that `copy` is also a method in pydantic's `BaseModel`, which is overriden here. This might be a case where we don't want the use super's copy but having a flag which by default is False (for inference) gives us almost the same behavior.

2021-06-16 16:19 UTC, brollb commented
Looks great!

2021-06-16 16:19 UTC, brollb approved these changes

2021-06-16 16:23 UTC, merged