Additional Configuration Options for OSD Viewer via Query params. Closes #70
symbench/scm pull request #78
Opened 2021-06-14 16:49 UTC by umesh-timalsina

Here's a checklist of deliverables for this PR:

- [x] Detect Single vs. Multi Image modes based on query param `images`. 
- [ ] Test and Handle Annotorious plugins based on sequence mode/ single image mode. Either should work
- [ ] Add Options to load annotations from a json file (query source image from json file as well)
- [ ] Add Options to load annotations from a zip file (query source image from zip file as well) ?
- [ ] Root annotation and Root Image for template matching (Optional/ Can be handled by different issue/PR).

2021-06-21 17:38 UTC, brollb commented on js/circuit-annotator/scripts/createDatasetIndex.js
> +    return `<li><a href="/index.html?images=${filename}">${filename}</a></li>`;
I don't think this is necessary to add to this PR but, if so, it might be nice to add a flag to either generate the HTML the old way or this way.

2021-06-22 03:51 UTC, umesh-timalsina commented on js/circuit-annotator/scripts/createDatasetIndex.js
> +
> I don't think this is necessary to add to this PR but, if so, it might be nice to add a flag to either generate the HTML the old way or this way.

In relation to https://github.com/symbench/scm/pull/78/commits/7bee747c0528a84dc84809499d29ed07d18f624b#r655581253

There is a function here to generate a single link for all images.

2021-06-22 04:00 UTC, umesh-timalsina commented
This PR is ready for testing. I think we should iterate over it and support collection mode configuration separately.

2021-06-23 18:28 UTC, brollb commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        if(annotationUrls) {
As a stylistic comment, it might be nice to pass this in as an argument (eg, `fetchAnnotations(annotationUrls)`) to make it more obvious where the annotations are coming from when it is called.

It also might be nice to always return an object/list rather than sometimes returning `undefined`.

2021-06-23 18:32 UTC, brollb requested changes
I should have marked the review as requesting changes. I have been trying to load "http://localhost:5000/index.html?images=ltspice/astable.png" without any luck...

2021-06-23 18:34 UTC, brollb commented on js/circuit-annotator/src/App.svelte
> +	const images = qsDict.images?.split(',');
It might not be bad to filter out `''` here and on the next line.

2021-06-23 18:42 UTC, umesh-timalsina commented on js/circuit-annotator/src/Components/OpenSeadragon/OpenSeadragon.svelte
> +        allImages = images || initialAnnotations ? Object.keys(initialAnnotations) : [defaultImage];
Too Bad, I need to revisit precedence in javascript.

2021-06-30 15:42 UTC, merged